-- AlterTable
ALTER TABLE "Wallet" ADD COLUMN "usedSms" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "usedCalls" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "periodStart" TIMESTAMP(3),
ADD COLUMN "recharging" BOOLEAN NOT NULL DEFAULT false;
